#!/bin/bash

cd /src/$BUILD_CODE
sed -e "s@REPLACE_IMAGENAME@$IMAGE_NAME@" ./7.2/docker-compose.test.yml -i
docker-compose -f ./7.2/docker-compose.test.yml up -d
docker-compose -f ./7.2/docker-compose.test.yml run sut /dockerize -wait http://127.0.0.1 -timeout 30s
