#!/bin/bash

cd /src/$BUILD_CODE
sed
sed -v
gsed
sed -e "s/REPLACE_IMAGENAME/$IMAGE_NAME/" ./7.2/docker-compose.test.yml -i
docker-compose -f ./7.2/docker-compose.test.yml up -d
./dockerize -wait http://127.0.0.1:8080 -timeout 30s
curl -f --retry 10 --retry-delay 3 http://127.0.0.1:8080
