#!/bin/bash
set -o pipefail

curl -sL https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz -o dockerize-linux-amd64.tar.gz | tar xvzf -

git clone https://github.com/mobingilabs/default-site-php -b dir_public test/code
