#!/bin/bash

cd /src/$BUILD_CODE
TARGETDIR=`dirname $DOCKERFILE_PATH`
sed -e "s@REPLACE_IMAGENAME@$IMAGE_NAME@g" ./${TARGETDIR}/docker-compose.test.yml -i
docker-compose version
docker-compose -f ./${TARGETDIR}/docker-compose.test.yml up -d
docker-compose -f ./${TARGETDIR}/docker-compose.test.yml exec -T sut /dockerize -wait http://127.0.0.1/ -timeout 30s
docker-compose -f ./${TARGETDIR}/docker-compose.test.yml exec -T sutc /dockerize -wait http://127.0.0.1/ -timeout 30s
